In [1]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import time

C:\Users\PHU\AppData\Local\Temp\ipykernel_23092\1439919409.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Define the URL
url = "https://api.tomorrow.io/v4/weather/realtime?location=10.7829647,106.670745&apikey=Ez2hSkCFqMrvsXGs56HWnk7eWcKGwGP8"

In [3]:
# Initialize an empty list to store the responses
dataframes = []

# Function to call the API, add response data to list of dataframes, and save to CSV
def call_api_and_save():
    try:
        headers = {"accept": "application/json"}
        response = requests.get(url, headers=headers)
        response_data = response.json()
        print(response_data)
        # Assuming the response contains a 'data' field with relevant information
        if 'data' in response_data:
            # Convert response data to dataframe
            new_data = pd.DataFrame(response_data)
            
            # Append dataframe to the list
            dataframes.append(new_data)
            
            # Concatenate all dataframes in the list
            combined_dataframe = pd.concat(dataframes, ignore_index=True)
            
            # Save combined dataframe to CSV
            combined_dataframe.to_csv('../data/weather data/weather_data_3-3.csv', index=False)
            
            print("Data saved successfully.")
        else:
            print("No data found in response.")
    except Exception as e:
        print("Error occurred:", e)

# Call the API and save data every 15 minutes
for i in range(30):
    call_api_and_save()
    time.sleep(900)  # 900 seconds = 15 minutes

{'data': {'time': '2024-03-03T15:16:00Z', 'values': {'cloudBase': 0.77, 'cloudCeiling': 0.77, 'cloudCover': 84, 'dewPoint': 22, 'freezingRainIntensity': 0, 'humidity': 70, 'precipitationProbability': 0, 'pressureSurfaceLevel': 1011.98, 'rainIntensity': 0, 'sleetIntensity': 0, 'snowIntensity': 0, 'temperature': 28, 'temperatureApparent': 30.67, 'uvHealthConcern': 0, 'uvIndex': 0, 'visibility': 9.99, 'weatherCode': 1001, 'windDirection': 140, 'windGust': 8.81, 'windSpeed': 5.69}}, 'location': {'lat': 10.7829647, 'lon': 106.670745}}
Data saved successfully.
{'data': {'time': '2024-03-03T15:31:00Z', 'values': {'cloudBase': 0.77, 'cloudCeiling': 0.77, 'cloudCover': 85, 'dewPoint': 22, 'freezingRainIntensity': 0, 'humidity': 70, 'precipitationProbability': 0, 'pressureSurfaceLevel': 1011.99, 'rainIntensity': 0, 'sleetIntensity': 0, 'snowIntensity': 0, 'temperature': 28, 'temperatureApparent': 30.67, 'uvHealthConcern': 0, 'uvIndex': 0, 'visibility': 9.99, 'weatherCode': 1001, 'windDirection': 140, 'windGust': 8.88, 'windSpeed': 5.69}}, 'location': {'lat': 10.7829647, 'lon': 106.670745}}
Data saved successfully.
{'data': {'time': '2024-03-03T15:46:00Z', 'values': {'cloudBase': 0.65, 'cloudCeiling': 0.65, 'cloudCover': 87, 'dewPoint': 22, 'freezingRainIntensity': 0, 'humidity': 74, 'precipitationProbability': 0, 'pressureSurfaceLevel': 1012, 'rainIntensity': 0, 'sleetIntensity': 0, 'snowIntensity': 0, 'temperature': 27, 'temperatureApparent': 29.2, 'uvHealthConcern': 0, 'uvIndex': 0, 'visibility': 9.99, 'weatherCode': 1001, 'windDirection': 130, 'windGust': 9, 'windSpeed': 6.69}}, 'location': {'lat': 10.7829647, 'lon': 106.670745}}
Data saved successfully.
{'data': {'time': '2024-03-03T16:01:00Z', 'values': {'cloudBase': 0.65, 'cloudCeiling': 0.65, 'cloudCover': 88, 'dewPoint': 22, 'freezingRainIntensity': 0, 'humidity': 74, 'precipitationProbability': 0, 'pressureSurfaceLevel': 1012, 'rainIntensity': 0, 'sleetIntensity': 0, 'snowIntensity': 0, 'temperature': 27, 'temperatureApparent': 29.2, 'uvHealthConcern': 0, 'uvIndex': 0, 'visibility': 9.99, 'weatherCode': 1001, 'windDirection': 130, 'windGust': 9, 'windSpeed': 6.69}}, 'location': {'lat': 10.7829647, 'lon': 106.670745}}
Data saved successfully.
{'data': {'time': '2024-03-03T16:16:00Z', 'values': {'cloudBase': 0.65, 'cloudCeiling': 0.65, 'cloudCover': 89, 'dewPoint': 22, 'freezingRainIntensity': 0, 'humidity': 74, 'precipitationProbability': 0, 'pressureSurfaceLevel': 1011.91, 'rainIntensity': 0, 'sleetIntensity': 0, 'snowIntensity': 0, 'temperature': 27, 'temperatureApparent': 29.2, 'uvHealthConcern': 0, 'uvIndex': 0, 'visibility': 9.99, 'weatherCode': 1001, 'windDirection': 130, 'windGust': 9.13, 'windSpeed': 5.69}}, 'location': {'lat': 10.7829647, 'lon': 106.670745}}
Data saved successfully.

In [2]:
url = "https://api.tomorrow.io/v4/timelines?apikey=Ez2hSkCFqMrvsXGs56HWnk7eWcKGwGP8"

In [3]:
payload = {
    "location": "10.7829647,106.670745",
    "fields": ["temperature", "cloudBase", "cloudCeiling", "cloudCover", "dewPoint", "freezingRainIntensity", "humidity", "precipitationProbability", "pressureSurfaceLevel", "rainIntensity", "sleetIntensity", "snowIntensity", "temperatureApparent", "uvHealthConcern", "uvIndex", "visibility", "weatherCode", "windDirection", "windGust", "windSpeed"],
    "units": "metric",
    "timesteps": ["15m"],
    "startTime": "nowMinus24h",
    "endTime": "now",
    "timezone": "auto"
}
headers = {
    "accept": "application/json",
    "Accept-Encoding": "gzip",
    "content-type": "application/json"
}

In [4]:
response = requests.post(url, json=payload, headers=headers)

print(response.text)

{"data":{"timelines":[{"timestep":"15m","endTime":"2024-03-23T00:07:00+07:00","startTime":"2024-03-22T00:07:00+07:00","intervals":[{"startTime":"2024-03-22T00:07:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":5,"pressureSurfaceLevel":1010.85,"rainIntensity":0.15,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":150,"windGust":5.85,"windSpeed":4.13}},{"startTime":"2024-03-22T00:22:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":5,"pressureSurfaceLevel":1010.67,"rainIntensity":0.25,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":150,"windGust":5.75,"windSpeed":3.89}},{"startTime":"2024-03-22T00:37:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":5,"pressureSurfaceLevel":1010.48,"rainIntensity":0.13,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":130,"windGust":5.66,"windSpeed":3.63}},{"startTime":"2024-03-22T00:52:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":5,"pressureSurfaceLevel":1010.3,"rainIntensity":1.27,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":4200,"windDirection":130,"windGust":5.57,"windSpeed":4.09}},{"startTime":"2024-03-22T01:07:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":5,"pressureSurfaceLevel":1010.15,"rainIntensity":0.13,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5.56,"windSpeed":4.63}},{"startTime":"2024-03-22T01:22:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1010.02,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5.51,"windSpeed":4.16}},{"startTime":"2024-03-22T01:37:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.9,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5.29,"windSpeed":3.63}},{"startTime":"2024-03-22T01:52:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.77,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5.1,"windSpeed":3.63}},{"startTime":"2024-03-22T02:07:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.62,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5,"windSpeed":3.63}},{"startTime":"2024-03-22T02:22:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.45,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":4.94,"windSpeed":3.63}},{"startTime":"2024-03-22T02:37:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.28,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.67,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":4.88,"windSpeed":3.63}},{"startTime":"2024-03-22T02:52:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21.53,"freezingRainIntensity":0,"humidity":68.13,"precipitationProbability":0,"pressureSurfaceLevel":1009.1,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.42,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5.25,"windSpeed":4.59}},{"startTime":"2024-03-22T03:07:00+07:00","values":{"cloudBase":0.89,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":66,"precipitationProbability":0,"pressureSurfaceLevel":1009.01,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":30.15,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":130,"windGust":5.69,"windSpeed":5.69}},{"startTime":"2024-03-22T03:22:00+07:00","values":{"cloudBase":0.89,"cloudCeiling":null,"cloudCover":44,"dewPoint":21.47,"freezingRainIntensity":0,"humidity":69.73,"precipitationProbability":0,"pressureSurfaceLevel":1009.02,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27.53,"temperatureApparent":29.76,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":130,"windGust":5.51,"windSpeed":4.72}},{"startTime":"2024-03-22T03:37:00+07:00","values":{"cloudBase":0.65,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":74,"precipitationProbability":0,"pressureSurfaceLevel":1009.02,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":29.2,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5.46,"windSpeed":3.63}},{"startTime":"2024-03-22T03:52:00+07:00","values":{"cloudBase":0.65,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":74,"precipitationProbability":0,"pressureSurfaceLevel":1009.03,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":29.2,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":140,"windGust":5.71,"windSpeed":3.39}},{"startTime":"2024-03-22T04:07:00+07:00","values":{"cloudBase":0.65,"cloudCeiling":null,"cloudCover":44,"dewPoint":22,"freezingRainIntensity":0,"humidity":74,"precipitationProbability":0,"pressureSurfaceLevel":1009.02,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":29.2,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":130,"windGust":5.75,"windSpeed":3.13}},{"startTime":"2024-03-22T04:22:00+07:00","values":{"cloudBase":0.65,"cloudCeiling":null,"cloudCover":44,"dewPoint":21.53,"freezingRainIntensity":0,"humidity":72.13,"precipitationProbability":0,"pressureSurfaceLevel":1009.01,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":29.04,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":130,"windGust":5.66,"windSpeed":3.59}},{"startTime":"2024-03-22T04:37:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1008.99,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":120,"windGust":5.51,"windSpeed":4.36}},{"startTime":"2024-03-22T04:52:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1008.98,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":110,"windGust":5.35,"windSpeed":4.63}},{"startTime":"2024-03-22T05:07:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.05,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":110,"windGust":5.17,"windSpeed":4.63}},{"startTime":"2024-03-22T05:22:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.23,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":110,"windGust":4.85,"windSpeed":4.63}},{"startTime":"2024-03-22T05:37:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.41,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":110,"windGust":4.54,"windSpeed":4.39}},{"startTime":"2024-03-22T05:52:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.59,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":120,"windGust":4.26,"windSpeed":4.13}},{"startTime":"2024-03-22T06:07:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1009.8,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1101,"windDirection":120,"windGust":4.21,"windSpeed":4.13}},{"startTime":"2024-03-22T06:22:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":31.87,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1010.04,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":4.34,"windSpeed":3.43}},{"startTime":"2024-03-22T06:37:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":17.07,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1010.29,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1100,"windDirection":110,"windGust":4.43,"windSpeed":2.63}},{"startTime":"2024-03-22T06:52:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":15.07,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1010.53,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":4.56,"windSpeed":2.63}},{"startTime":"2024-03-22T07:07:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":13.53,"dewPoint":21,"freezingRainIntensity":0,"humidity":70,"precipitationProbability":0,"pressureSurfaceLevel":1010.73,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27,"temperatureApparent":28.86,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":4.8,"windSpeed":2.63}},{"startTime":"2024-03-22T07:22:00+07:00","values":{"cloudBase":0.77,"cloudCeiling":null,"cloudCover":13,"dewPoint":21,"freezingRainIntensity":0,"humidity":68.13,"precipitationProbability":0,"pressureSurfaceLevel":1010.88,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":27.47,"temperatureApparent":29.48,"uvHealthConcern":0,"uvIndex":0,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":5.18,"windSpeed":2.63}},{"startTime":"2024-03-22T07:37:00+07:00","values":{"cloudBase":0.89,"cloudCeiling":null,"cloudCover":12.53,"dewPoint":20.53,"freezingRainIntensity":0,"humidity":64.13,"precipitationProbability":0,"pressureSurfaceLevel":1011.02,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":29.93,"uvHealthConcern":1,"uvIndex":2,"visibility":9.99,"weatherCode":1100,"windDirection":110,"windGust":5.58,"windSpeed":2.63}},{"startTime":"2024-03-22T07:52:00+07:00","values":{"cloudBase":1.02,"cloudCeiling":null,"cloudCover":12,"dewPoint":20,"freezingRainIntensity":0,"humidity":62,"precipitationProbability":0,"pressureSurfaceLevel":1011.17,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":29.68,"uvHealthConcern":1,"uvIndex":2,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":5.99,"windSpeed":2.63}},{"startTime":"2024-03-22T08:07:00+07:00","values":{"cloudBase":1.02,"cloudCeiling":null,"cloudCover":12.93,"dewPoint":20,"freezingRainIntensity":0,"humidity":62,"precipitationProbability":0,"pressureSurfaceLevel":1011.27,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28,"temperatureApparent":29.68,"uvHealthConcern":1,"uvIndex":2,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":6.33,"windSpeed":2.63}},{"startTime":"2024-03-22T08:22:00+07:00","values":{"cloudBase":1.02,"cloudCeiling":null,"cloudCover":15.4,"dewPoint":20,"freezingRainIntensity":0,"humidity":60.13,"precipitationProbability":0,"pressureSurfaceLevel":1011.3,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":28.47,"temperatureApparent":30.18,"uvHealthConcern":1,"uvIndex":2,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":6.65,"windSpeed":2.63}},{"startTime":"2024-03-22T08:37:00+07:00","values":{"cloudBase":1.17,"cloudCeiling":null,"cloudCover":18.4,"dewPoint":20,"freezingRainIntensity":0,"humidity":58,"precipitationProbability":0,"pressureSurfaceLevel":1011.33,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":29,"temperatureApparent":30.73,"uvHealthConcern":2,"uvIndex":5,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":6.96,"windSpeed":2.63}},{"startTime":"2024-03-22T08:52:00+07:00","values":{"cloudBase":1.17,"cloudCeiling":null,"cloudCover":20.93,"dewPoint":20,"freezingRainIntensity":0,"humidity":58,"precipitationProbability":0,"pressureSurfaceLevel":1011.36,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":29,"temperatureApparent":30.73,"uvHealthConcern":2,"uvIndex":5,"visibility":9.99,"weatherCode":1100,"windDirection":120,"windGust":7.21,"windSpeed":2.63}},{"startTime":"2024-03-22T09:07:00+07:00","values":{"cloudBase":1.17,"cloudCeiling":null,"cloudCover":26.67,"dewPoint":20,"freezingRainIntensity":0,"humidity":56.13,"precipitationProbability":0,"pressureSurfaceLevel":1011.36,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":29.64,"temperatureApparent":31.49,"uvHealthConcern":2,"uvIndex":5,"visibility":12.8,"weatherCode":1100,"windDirection":120,"windGust":7.46,"windSpeed":3.12}},{"startTime":"2024-03-22T09:22:00+07:00","values":{"cloudBase":1.34,"cloudCeiling":null,"cloudCover":36.67,"dewPoint":19.53,"freezingRainIntensity":0,"humidity":51.67,"precipitationProbability":0,"pressureSurfaceLevel":1011.31,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":30.67,"temperatureApparent":32.39,"uvHealthConcern":2,"uvIndex":5,"visibility":13.2,"weatherCode":1100,"windDirection":113.31,"windGust":7.71,"windSpeed":4.62}},{"startTime":"2024-03-22T09:37:00+07:00","values":{"cloudBase":1.53,"cloudCeiling":null,"cloudCover":46.2,"dewPoint":19,"freezingRainIntensity":0,"humidity":49,"precipitationProbability":0,"pressureSurfaceLevel":1011.27,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":31,"temperatureApparent":32.42,"uvHealthConcern":3,"uvIndex":9,"visibility":9.99,"weatherCode":1101,"windDirection":120,"windGust":7.9,"windSpeed":5.69}},{"startTime":"2024-03-22T09:52:00+07:00","values":{"cloudBase":1.53,"cloudCeiling":1.53,"cloudCover":55.67,"dewPoint":18.53,"freezingRainIntensity":0,"humidity":46.2,"precipitationProbability":0,"pressureSurfaceLevel":1011.23,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":31.47,"temperatureApparent":32.63,"uvHealthConcern":3,"uvIndex":9,"visibility":9.99,"weatherCode":1101,"windDirection":120,"windGust":8.15,"windSpeed":5.43}},{"startTime":"2024-03-22T10:07:00+07:00","values":{"cloudBase":1.8,"cloudCeiling":1.8,"cloudCover":57.27,"dewPoint":18,"freezingRainIntensity":0,"humidity":43,"precipitationProbability":0,"pressureSurfaceLevel":1011.08,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":32,"temperatureApparent":32.84,"uvHealthConcern":3,"uvIndex":9,"visibility":9.99,"weatherCode":1101,"windDirection":110,"windGust":8.25,"windSpeed":5.13}},{"startTime":"2024-03-22T10:22:00+07:00","values":{"cloudBase":1.8,"cloudCeiling":1.8,"cloudCover":48.8,"dewPoint":18.47,"freezingRainIntensity":0,"humidity":43.47,"precipitationProbability":0,"pressureSurfaceLevel":1010.82,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":32.47,"temperatureApparent":33.68,"uvHealthConcern":3,"uvIndex":9,"visibility":9.99,"weatherCode":1101,"windDirection":110,"windGust":8.19,"windSpeed":5.39}},{"startTime":"2024-03-22T10:37:00+07:00","values":{"cloudBase":1.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":19,"freezingRainIntensity":0,"humidity":44,"precipitationProbability":0,"pressureSurfaceLevel":1010.56,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":33,"temperatureApparent":34.7,"uvHealthConcern":5,"uvIndex":11,"visibility":9.99,"weatherCode":1101,"windDirection":120,"windGust":8.19,"windSpeed":5.69}},{"startTime":"2024-03-22T10:52:00+07:00","values":{"cloudBase":1.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":19,"freezingRainIntensity":0,"humidity":44,"precipitationProbability":0,"pressureSurfaceLevel":1010.29,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":33,"temperatureApparent":34.7,"uvHealthConcern":5,"uvIndex":11,"visibility":9.99,"weatherCode":1101,"windDirection":120,"windGust":8.19,"windSpeed":5.19}},{"startTime":"2024-03-22T11:07:00+07:00","values":{"cloudBase":1.77,"cloudCeiling":null,"cloudCover":44,"dewPoint":19,"freezingRainIntensity":0,"humidity":44,"precipitationProbability":0,"pressureSurfaceLevel":1009.97,"rainIntensity":0,"sleetIntensity":0,"snowIntensity":0,"temperature":33,"temperatureApparen

In [5]:
# Convert response data to dataframe and save to CSV
response_data = response.json()
new_data = pd.DataFrame(response_data)
#separate each start time to a row
new_data = new_data.explode('data')
#separate each data to a column
new_data = pd.concat([new_data.drop(['data'], axis=1), new_data['data'].apply(pd.Series)], axis=1)
new_data.head()

# Save combined dataframe to json
new_data.to_json('../data/weather data/weather_data_22-3.json', orient='records')

In [22]:
#apply pd.Series to intervals column, turn it into a dataframe
intervals = new_data['intervals'].apply(pd.Series)

In [23]:
intervals.head()

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
timelines,"{'startTime': '2024-03-15T22:44:00+07:00', 'va...","{'startTime': '2024-03-15T22:59:00+07:00', 'va...","{'startTime': '2024-03-15T23:14:00+07:00', 'va...","{'startTime': '2024-03-15T23:29:00+07:00', 'va...","{'startTime': '2024-03-15T23:44:00+07:00', 'va...","{'startTime': '2024-03-15T23:59:00+07:00', 'va...","{'startTime': '2024-03-16T00:14:00+07:00', 'va...","{'startTime': '2024-03-16T00:29:00+07:00', 'va...","{'startTime': '2024-03-16T00:44:00+07:00', 'va...","{'startTime': '2024-03-16T00:59:00+07:00', 'va...",...,"{'startTime': '2024-03-16T20:29:00+07:00', 'va...","{'startTime': '2024-03-16T20:44:00+07:00', 'va...","{'startTime': '2024-03-16T20:59:00+07:00', 'va...","{'startTime': '2024-03-16T21:14:00+07:00', 'va...","{'startTime': '2024-03-16T21:29:00+07:00', 'va...","{'startTime': '2024-03-16T21:44:00+07:00', 'va...","{'startTime': '2024-03-16T21:59:00+07:00', 'va...","{'startTime': '2024-03-16T22:14:00+07:00', 'va...","{'startTime': '2024-03-16T22:29:00+07:00', 'va...","{'startTime': '2024-03-16T22:44:00+07:00', 'va..."

In [35]:
#for each column in intervals, there are 'startTime' and 'values' columns, with each value of startTime has a corresponding value in 'values'
start_time = pd.DataFrame()
values = pd.DataFrame()
for column in intervals.columns:
    start_time[column] = intervals[column].apply(lambda x: x['startTime'])
    values[column] = intervals[column].apply(lambda x: x['values'])


values = values.apply(lambda x: x.apply(pd.Series))

ValueError: If using all scalar values, you must pass an index

In [34]:
values.head()

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
timelines,"{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.39, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.26, 'cloudCeiling': None, 'clo...",...,"{'cloudBase': None, 'cloudCeiling': None, 'clo...","{'cloudBase': None, 'cloudCeiling': None, 'clo...","{'cloudBase': None, 'cloudCeiling': None, 'clo...","{'cloudBase': 1.03, 'cloudCeiling': None, 'clo...","{'cloudBase': 1.03, 'cloudCeiling': None, 'clo...","{'cloudBase': 1.03, 'cloudCeiling': None, 'clo...","{'cloudBase': 1.03, 'cloudCeiling': None, 'clo...","{'cloudBase': 1.03, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.89, 'cloudCeiling': None, 'clo...","{'cloudBase': 0.89, 'cloudCeiling': None, 'clo..."